name: CI

on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}
jobs:
  Dependencies:
    runs-on: Ubuntu-22.04
    steps:
      - name: Build and test
        run: |
          sudo apt install -y libelf-dev elfutils
          sudo apt install -y binutils cmake make
          sudo apt install -y pylint python3-dev
  Checkout:
    runs-on: ubuntu-22.04
    needs: Dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  Build:
    runs-on: Ubuntu-22.04
    needs: [Dependencies, Checkout]
    steps:
      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make install
          make test
        shell: bash
