name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}

jobs:
  Dependencies:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y libelf-dev elfutils
          sudo apt install -y binutils cmake make
          sudo apt install -y pylint python3-dev
          dpkg-query -s libelf-dev
  Checkout:
    runs-on: ubuntu-22.04
    needs: Dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test
        run: |
          dpkg-query -s libelf-dev
          ls -lah
          pwd
          mkdir build
          cd build
          cmake ..
          make
          make install
          make test
        shell: bash
