name: CI

on: [push, pull_request]

jobs:
  py-libelf-bulid-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y libelf-dev elfutils
          sudo apt install -y binutils cmake make
          sudo apt install -y pylint python3-dev
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and test
        run: |
          ls -lah
          pwd
          mkdir build
          cd build
          cmake ..
          make
          make install
          make test
        shell: bash
